"""initial claim schema

Revision ID: 53a58d50e1e4
Revises: none
Create Date: 2026-09-26 11:20:03.537622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53a58d50e1e4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_version_id', sa.String(length=32), nullable=False),
    sa.Column('model_type', sa.String(length=10), nullable=False),
    sa.Column('model_name', sa.String(length=150), nullable=False),
    sa.Column('version', sa.String(length=80), nullable=False),
    sa.Column('artifact_path', sa.Text(), nullable=False),
    sa.Column('training_dataset_version', sa.String(length=100), nullable=False),
    sa.Column('metrics_json', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('retired_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("model_type IN ('python','gtm')", name='ck_models_type'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model_type', 'model_name', 'version', name='uq_model_release'),
    sa.UniqueConstraint('model_version_id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("role IN ('customer','service_center_employee','reviewer','administrator')", name='ck_users_role'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=False),
    sa.Column('model_number', sa.String(length=100), nullable=False),
    sa.Column('serial_number', sa.String(length=150), nullable=False),
    sa.Column('purchase_date', sa.Date(), nullable=False),
    sa.Column('purchase_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('retailer', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('purchase_price >= 0', name='ck_products_price'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id')
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_products_serial_number'), ['serial_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_user_id'), ['user_id'], unique=False)

    op.create_table('warranties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('warranty_id', sa.String(length=32), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=200), nullable=False),
    sa.Column('warranty_type', sa.String(length=20), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=False),
    sa.Column('coverage_duration_months', sa.Integer(), nullable=False),
    sa.Column('coverage_conditions', sa.JSON(), nullable=False),
    sa.Column('exclusions', sa.JSON(), nullable=False),
    sa.Column('extended_warranty', sa.Boolean(), nullable=False),
    sa.Column('service_center_requirements', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("warranty_type IN ('standard','extended')", name='ck_warranties_type'),
    sa.CheckConstraint('coverage_duration_months > 0', name='ck_warranties_duration'),
    sa.CheckConstraint('expiry_date >= start_date', name='ck_warranties_dates'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('warranty_id')
    )
    with op.batch_alter_table('warranties', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_warranties_expiry_date'), ['expiry_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_warranties_product_id'), ['product_id'], unique=False)

    op.create_table('claims',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('claim_id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('warranty_id', sa.Integer(), nullable=False),
    sa.Column('fault_date', sa.Date(), nullable=False),
    sa.Column('fault_type', sa.String(length=100), nullable=False),
    sa.Column('fault_description', sa.Text(), nullable=False),
    sa.Column('damage_type', sa.String(length=100), nullable=True),
    sa.Column('submission_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('final_decision', sa.String(length=32), nullable=True),
    sa.Column('manual_review_required', sa.Boolean(), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("final_decision IS NULL OR final_decision IN ('likely_valid','likely_invalid','manual_review_required')", name='ck_claims_decision'),
    sa.CheckConstraint("status IN ('draft','submitted','under_evaluation','additional_information_required','manual_review','approved','rejected','closed')", name='ck_claims_status'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['warranty_id'], ['warranties.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('claim_id')
    )
    with op.batch_alter_table('claims', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_claims_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_claims_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_claims_submission_date'), ['submission_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_claims_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_claims_warranty_id'), ['warranty_id'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('audit_id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('claim_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.String(length=80), nullable=False),
    sa.Column('old_values', sa.JSON(), nullable=True),
    sa.Column('new_values', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('audit_id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_claim_id'), ['claim_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_user_id'), ['user_id'], unique=False)

    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.String(length=32), nullable=False),
    sa.Column('claim_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('warranty_id', sa.Integer(), nullable=True),
    sa.Column('document_type', sa.String(length=40), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('stored_filename', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('storage_path', sa.Text(), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('ocr_status', sa.String(length=30), nullable=False),
    sa.Column('ocr_text', sa.Text(), nullable=True),
    sa.Column('extracted_data', sa.JSON(), nullable=True),
    sa.Column('verified_data', sa.JSON(), nullable=True),
    sa.Column('uploaded_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("document_type IN ('receipt','invoice','warranty_card','product_image','serial_number_image','fault_evidence','diagnostic_report','repair_report','other')", name='ck_documents_type'),
    sa.CheckConstraint('(claim_id IS NOT NULL) OR (product_id IS NOT NULL) OR (warranty_id IS NOT NULL)', name='ck_documents_parent'),
    sa.CheckConstraint('file_size >= 0', name='ck_documents_size'),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['warranty_id'], ['warranties.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id')
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documents_claim_id'), ['claim_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_file_hash'), ['file_hash'], unique=False)

    op.create_table('gtm_predictions',
    sa.Column('prediction_id', sa.String(length=32), nullable=False),
    sa.Column('claim_summary_card_path', sa.Text(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('claim_id', sa.Integer(), nullable=False),
    sa.Column('model_version_id', sa.Integer(), nullable=False),
    sa.Column('predicted_class', sa.String(length=30), nullable=False),
    sa.Column('confidence_valid', sa.Numeric(precision=7, scale=6), nullable=False),
    sa.Column('confidence_invalid', sa.Numeric(precision=7, scale=6), nullable=False),
    sa.Column('confidence_manual_review', sa.Numeric(precision=7, scale=6), nullable=False),
    sa.Column('top_confidence', sa.Numeric(precision=7, scale=6), nullable=False),
    sa.Column('inference_duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("predicted_class IN ('valid','invalid','manual_review')", name='ck_gtm_class'),
    sa.CheckConstraint('confidence_invalid >= 0 AND confidence_invalid <= 1', name='ck_gtm_confidence_invalid'),
    sa.CheckConstraint('confidence_manual_review >= 0 AND confidence_manual_review <= 1', name='ck_gtm_confidence_manual_review'),
    sa.CheckConstraint('confidence_valid >= 0 AND confidence_valid <= 1', name='ck_gtm_confidence_valid'),
    sa.CheckConstraint('inference_duration_ms IS NULL OR inference_duration_ms >= 0', name='ck_gtm_duration'),
    sa.CheckConstraint('top_confidence >= 0 AND top_confidence <= 1', name='ck_gtm_top_confidence'),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prediction_id')
    )
    with op.batch_alter_table('gtm_predictions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gtm_predictions_claim_id'), ['claim_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_gtm_predictions_model_version_id'), ['model_version_id'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notification_id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('claim_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=60), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('notification_id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_claim_id'), ['claim_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_notifications_user_unread', ['user_id', 'is_read'], unique=False)

    op.create_table('python_predictions',
    sa.Column('prediction_id', sa.String(length=32), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('claim_id', sa.Integer(), nullable=False),
    sa.Column('model_version_id', sa.Integer(), nullable=False),
    sa.Column('predicted_class', sa.String(length=30), nullable=False),
    sa.Column('confidence_valid', sa.Numeric(precision=7, scale=6), nullable=False),
    sa.Column('confidence_invalid', sa.Numeric(precision=7, scale=6), nullable=False),
    sa.Column('confidence_manual_review', sa.Numeric(precision=7, scale=6), nullable=False),
    sa.Column('top_confidence', sa.Numeric(precision=7, scale=6), nullable=False),
    sa.Column('inference_duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("predicted_class IN ('valid','invalid','manual_review')", name='ck_python_class'),
    sa.CheckConstraint('confidence_invalid >= 0 AND confidence_invalid <= 1', name='ck_python_confidence_invalid'),
    sa.CheckConstraint('confidence_manual_review >= 0 AND confidence_manual_review <= 1', name='ck_python_confidence_manual_review'),
    sa.CheckConstraint('confidence_valid >= 0 AND confidence_valid <= 1', name='ck_python_confidence_valid'),
    sa.CheckConstraint('inference_duration_ms IS NULL OR inference_duration_ms >= 0', name='ck_python_duration'),
    sa.CheckConstraint('top_confidence >= 0 AND top_confidence <= 1', name='ck_python_top_confidence'),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prediction_id')
    )
    with op.batch_alter_table('python_predictions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_python_predictions_claim_id'), ['claim_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_python_predictions_model_version_id'), ['model_version_id'], unique=False)

    op.create_table('repair_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repair_id', sa.String(length=32), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('claim_id', sa.Integer(), nullable=True),
    sa.Column('repair_date', sa.Date(), nullable=False),
    sa.Column('service_center_name', sa.String(length=200), nullable=False),
    sa.Column('authorized_service_center', sa.Boolean(), nullable=False),
    sa.Column('parts_replaced', sa.Text(), nullable=True),
    sa.Column('repair_outcome', sa.String(length=100), nullable=False),
    sa.Column('repair_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('repair_cost >= 0', name='ck_repairs_cost'),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repair_id')
    )
    with op.batch_alter_table('repair_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_repair_history_claim_id'), ['claim_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_repair_history_product_id'), ['product_id'], unique=False)

    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('review_id', sa.String(length=32), nullable=False),
    sa.Column('claim_id', sa.Integer(), nullable=False),
    sa.Column('reviewer_user_id', sa.Integer(), nullable=False),
    sa.Column('decision', sa.String(length=32), nullable=False),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('override_applied', sa.Boolean(), nullable=False),
    sa.Column('previous_decision', sa.String(length=32), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("decision IN ('approve','reject','request_information','manual_review_continue')", name='ck_reviews_decision'),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reviewer_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('review_id')
    )
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reviews_claim_id'), ['claim_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reviews_reviewer_user_id'), ['reviewer_user_id'], unique=False)

    op.create_table('rule_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_result_id', sa.String(length=32), nullable=False),
    sa.Column('claim_id', sa.Integer(), nullable=False),
    sa.Column('rule_name', sa.String(length=150), nullable=False),
    sa.Column('rule_code', sa.String(length=80), nullable=False),
    sa.Column('rule_category', sa.String(length=80), nullable=False),
    sa.Column('result', sa.String(length=30), nullable=False),
    sa.Column('severity', sa.String(length=30), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('policy_version', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("result IN ('passed','failed','warning','manual_review')", name='ck_rules_result'),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rule_result_id')
    )
    with op.batch_alter_table('rule_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rule_results_claim_id'), ['claim_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rule_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rule_results_claim_id'))

    op.drop_table('rule_results')
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reviews_reviewer_user_id'))
        batch_op.drop_index(batch_op.f('ix_reviews_claim_id'))

    op.drop_table('reviews')
    with op.batch_alter_table('repair_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_repair_history_product_id'))
        batch_op.drop_index(batch_op.f('ix_repair_history_claim_id'))

    op.drop_table('repair_history')
    with op.batch_alter_table('python_predictions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_python_predictions_model_version_id'))
        batch_op.drop_index(batch_op.f('ix_python_predictions_claim_id'))

    op.drop_table('python_predictions')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index('ix_notifications_user_unread')
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_claim_id'))

    op.drop_table('notifications')
    with op.batch_alter_table('gtm_predictions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gtm_predictions_model_version_id'))
        batch_op.drop_index(batch_op.f('ix_gtm_predictions_claim_id'))

    op.drop_table('gtm_predictions')
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_file_hash'))
        batch_op.drop_index(batch_op.f('ix_documents_claim_id'))

    op.drop_table('documents')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_claim_id'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('claims', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_claims_warranty_id'))
        batch_op.drop_index(batch_op.f('ix_claims_user_id'))
        batch_op.drop_index(batch_op.f('ix_claims_submission_date'))
        batch_op.drop_index(batch_op.f('ix_claims_status'))
        batch_op.drop_index(batch_op.f('ix_claims_product_id'))

    op.drop_table('claims')
    with op.batch_alter_table('warranties', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_warranties_product_id'))
        batch_op.drop_index(batch_op.f('ix_warranties_expiry_date'))

    op.drop_table('warranties')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_user_id'))
        batch_op.drop_index(batch_op.f('ix_products_serial_number'))

    op.drop_table('products')
    op.drop_table('users')
    op.drop_table('model_versions')
    # ### end Alembic commands ###
